[tool.poetry]
name = "paperii"
version = "0.1.0"
description = "Yihao's paper II replication package"
authors = ["Superskyyy <superskyyy@outlook.com>"]
license = "None"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.8"
requests = "^2.28.1"
bs4 = "^0.0.1"
tqdm = "^4.64.1"
PyDriller = "^2.1"
feedparser = "^6.0.10"
pandas = "^2.0.1"
numpy = "^1.24.3"
matplotlib = "^3.7.1"
seaborn = "^0.12.2"
scikit-posthocs = "^0.7.0"
cliffs-delta = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
